server:
  port: ${SERVER.PORT:8090}
  timeout: ${SERVER.TIMEOUT:10}

api:
  UserCreate:
    method: POST
    url: user
  UserRead:
    method: GET
    url: user/{id}
  UsersRead:
    method: GET
    url: user
  UserUpdate:
    method: PUT
    url: user/{id}
  UserDelete:
    method: DELETE
    url: user/{id}

  ProductCreate:
    method: POST
    url: product
  ProductRead:
    method: GET
    url: product/{id}
  ProductsRead:
    method: GET
    url: product
  ProductUpdate:
    method: PUT
    url: product/{id}
  ProductDelete:
    method: DELETE
    url: product/{id}

  CartCreate:
    method: POST
    url: cart
  CartRead:
    method: GET
    url: cart/{id}
  CartUpdate:
    method: PUT
    url: cart/{id}
  CartDelete:
    method: DELETE
    url: cart/{id}

  AgeGroupCreate:
    method: POST
    url: agegroup
  AgeGroupRead:
    method: GET
    url: agegroup/{id}
  AgeGroupsRead:
    method: GET
    url: agegroup
  AgeGroupUpdate:
    method: PUT
    url: agegroup/{id}
  AgeGroupDelete:
    method: DELETE
    url: agegroup/{id}

  BrandCreate:
    method: POST
    url: brand
  BrandRead:
    method: GET
    url: brand/{id}
  BrandsRead:
    method: GET
    url: brand
  BrandUpdate:
    method: PUT
    url: brand/{id}
  BrandDelete:
    method: DELETE
    url: brand/{id}

  CategoryCreate:
   method: POST
   url: category
  CategoryRead:
   method: GET
   url: category/{id}
  CategoriesRead:
   method: GET
   url: category
  CategoryUpdate:
   method: PUT
   url: category/{id}
  CategoryDelete:
    method: DELETE
    url: category/{id}
