server:
  port: ${SERVER.PORT:8090}
  timeout: ${SERVER.TIMEOUT:10}

api:
  UserCreate:
    method: POST
    url: user
  UserRead:
    method: GET
    url: user/{id}
  UsersRead:
    method: GET
    url: user
  UserUpdate:
    method: PUT
    url: user/{id}
  UserDelete:
    method: DELETE
    url: user/{id}

  ProductCreate:
    method: POST
    url: product
  ProductRead:
    method: GET
    url: product/{id}
  ProductsRead:
    method: GET
    url: product
  ProductUpdate:
    method: PUT
    url: product/{id}
  ProductDelete:
    method: DELETE
    url: product/{id}

  CartCreate:
    method: POST
    url: cart
  CartRead:
    method: GET
    url: cart/{id}
  CartUpdate:
    method: PUT
    url: cart/{id}
  CartDelete:
    method: DELETE
    url: cart/{id}